---
description: 'Altre informazioni su: C26111'
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
ms.openlocfilehash: 45d75dba925e3083bad0281a4fb7fdcd7f4d38f7
ms.sourcegitcommit: d6af41e42699628c3e2e6063ec7b03931a49a098
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/11/2020
ms.locfileid: "97279260"
---
# <a name="c26111"></a>C26111

> avviso C26111: il chiamante non riesce a rilasciare il blocco \<lock> prima di chiamare la funzione \<func> .

L'annotazione `_Requires_lock_not_held_` impone una condizione preliminare che il numero di blocchi per il blocco specificato non può essere maggiore di zero quando viene chiamata la funzione. Quando una funzione non riesce a rilasciare il blocco prima di chiamare un'altra funzione, viene generato un avviso C26111.

## <a name="example"></a>Esempio

Nell'esempio seguente viene generato l'avviso C26111 perché la `_Requires_lock_not_held_` precondizione viene violata dalla chiamata a `DoNotLock` all'interno della sezione bloccata.

```cpp
typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```
